import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./pages/Navbar/Navbar";
import { CartProvider } from "./context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ApparelGlow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <CartProvider>
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
        </CartProvider>
  );
}